### ISSUE TITLE
[Bug]: Removal of set checkmarks in the "Forbidden Dashboards" not possible

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [pimcore/perspective-editor#132]
### Expected behavior

In the "Forbidden Dashboards", once set, the checkmarks can be removed again. Then they should be available again in the drop-down menu of the "Dashboard Assignment".

### Actual behavior

Setting the checkmarks in the "Forbidden Dashboards" works. Then the corresponding options are also no longer available in the dropdown of the "Dashboard Assignment".

If the once set checkmarks are to be removed again, it first looks as if this has worked (a success message is displayed). However, when you click on "Reload" and the editor has reloaded, you see that removing checkmarks which were previously set does not work: they are still set. Likewise, the corresponding options in the "Dashboard Assignment" dropdown are not available.

### Steps to reproduce

Reproduce these steps:
(e.g. on https://demo.pimcore.com/admin)

1. Set a check mark in the "Forbidden Dashboards" (e.g. "Modified Documents")
2. Click "Save" button.
3. Check if selection is available in the "Dashboard Assignment" dropdown (in the example "Modified Documents" is not available).
4. Remove the checkmark from the "Forbidden Dashboards".
5. Click "Save" button. (Success message appears.)
6. Check if selection is available in the "Dashboard Assignment" dropdown (in the example "Modified Documents" is still not available, although it should be available again). -- _This step is optional._
7. Reload the "Forbidden Dashboard" (e.g. by clicking on "Reload Button" or clicking on another tree node and back to "Forbidden Dashboards").
8. Result: removed check mark is still set.

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/perspective-editor/pull/153

**Comment by studio1gmbh-pimcore** [comment]
Thank you very much for fixing the issue with #153. As I could see, this is already planned for milestone 1.7.1 👍 . 

Unfortunately, some time has passed since you fixed the issue and merged the pull request. Therefore I would like to kindly ask if a release date for v1.7.1 is already planned.

**Comment by kingjia90** [comment]
Thank you for this reminder and your patience!

I had a quick check and confirmation that 1.7.1 will be released on next Tuesday (12th March).
Wish you a nice weekend in the meanwhile 😄
