### ISSUE TITLE
[Bug] Custom Views without icon are not shown in perspective

### ISSUE THREAD

**Issue by fashxp** [pimcore/perspective-editor#136]
### Expected behavior

Custom views are shown with default icon, or custom view cannot be saved

### Actual behavior

can create custom view without icon
when adding it to perspective, it is not shown

### Steps to reproduce

.

**Comment by robertSt7** [comment]
@fashxp I can not reproduce it, for me the custom view is displayed without an icon

**Comment by fashxp** [comment]
me neither, closed.
