### ISSUE TITLE
[Bug]: Allow Objects settings saved wrong as array instead of comma separated list

### ISSUE THREAD

**Issue by ascheider** [pimcore/perspective-editor#144]
### Expected behavior

I want to add a new object view with class assignment and save it without losing assigned classes on all existing views.

### Actual behavior

I create a new view of type object and assign the class. After save all class assignments are lost, because they are saved as array instead of comma separated list.

### Steps to reproduce

Create a view and assign classes to it and save the changes:
![image](https://github.com/pimcore/perspective-editor/assets/6016485/49945189-97e6-4334-84c3-be7f0204f57e)
Reload the admin and open View Editor again.
Add new view of type object and select also the object and save:
![image](https://github.com/pimcore/perspective-editor/assets/6016485/323f7d42-7ccc-44c2-bc64-4d7deb3414c8)
Reload the admin again and open the first view, object selection is gone:
![image](https://github.com/pimcore/perspective-editor/assets/6016485/07cb13fc-60c9-41ad-bd38-5d0ef7438411)
If you take a look in the database, the classes are stored as array, instead of comma separated list:
![image](https://github.com/pimcore/perspective-editor/assets/6016485/9304526e-09c4-47c9-9a5e-70ad13fc7f55)
If you reassign the class in the view and save again, the classes are stored as comma separated string again and view the objects correct.
![image](https://github.com/pimcore/perspective-editor/assets/6016485/33909c79-4061-47f9-8fd9-e030c36f49c6)

I tested the issue in pimcore 10.5 with Bundle Version 1.5.1 and also pimcore 11 with 1.6.1 and can reproduce it in both.
The bug is pretty critical, it breaks all existing views after creation of the new view.
If would be good if it can be fixed in both versions 1.5.2 and 1.6.2.

I inspected also the request, the data which is sent to the server has already wrong payload:
![image](https://github.com/pimcore/perspective-editor/assets/6016485/ac779a62-0fab-4674-8749-446e2f834230)
Maybe some serialization or encoding issue.

**Comment by dvesh3** [comment]
Fixed by #146

**Comment by ascheider** [comment]
@dvesh3 Thanks for the bugfix. Any chance to release the new versions soon?

**Comment by dvesh3** [comment]
@ascheider new release 1.6.2 is tagged which includes the fix.

**Comment by ascheider** [comment]
@dvesh3 I have one installation with 10.5.23 where it occures. The 1.6.2 is only compatible with from 10.6.
Can you please create also 1.5.2 for 10.5?
Thanks!

**Comment by dvesh3** [comment]
Sorry, 1.5 branch doesn't exist anymore for 10.5 as it reached EOL. Please use the [patch](https://patch-diff.githubusercontent.com/raw/pimcore/perspective-editor/pull/146.patch) in your project.
