### ISSUE TITLE
[Perspectives][ElementTree] Define position inline by adding folders left & right to the tree

### ISSUE THREAD

**Issue by fashxp** [pimcore/perspective-editor#18]
something like that: 

![image](https://user-images.githubusercontent.com/8792145/107653962-7f2aed00-6c82-11eb-9da1-b5e5f90f30af.png)

then activate d&d to move between folders.

**Comment by fashxp** [comment]
also define sorting implicitly with order in tree

**Comment by roland4432** [comment]
sorting is definitly a "yes"... 
not sure about the "left <-> right" thingy.. but it would be very convienent to have an indicator for the position the tree element would render to

**Comment by fashxp** [comment]
with indicator you mean?

**Comment by fashxp** [comment]
ping @roland4432 
what do you mean with 'indicator for the position' ? 
any other ideas?
