### ISSUE TITLE
[Perspectives] Custom View select not loaded properly

### ISSUE THREAD

**Issue by fashxp** [pimcore/perspective-editor#37]
![image](https://user-images.githubusercontent.com/8792145/109030318-fcfbe900-76c3-11eb-919a-11c23a81f0e9.png)

**Comment by roland4432** [comment]
I only get this error, when there are old ids stored in perspectives.php.
As soon as I replace the old testdata and save a perspective, then do a reload, everything is fine.

Can you confirm regular behavior, when the old testdata is wiped and replace with real data?

**Comment by roland4432** [comment]
Ah never mind. A complete reload shows the issue ;)

**Comment by fashxp** [comment]
yes, reload does the trick :) I'll have a look at it

**Comment by roland4432** [comment]
I think it's just a small timing issue. The value of the combobox is set before the store is loaded. Can check it these evening if u r busy

**Comment by fashxp** [comment]
nope, was some ID chaos.
