### ISSUE TITLE
[Bug]: Not possible to add classes

### ISSUE THREAD

**Issue by dpfahlbusch** [pimcore/perspective-editor#55]
### Expected behavior

Not possible to add classes in perspectives editor

### Actual behavior

Like mentioned here: https://github.com/pimcore/pimcore/discussions/10463

its currently not possible to add classes via perspectives editor, so we can not create a working perspective

### Steps to reproduce

* Open Perspective Editor
* No option available to add classes

**Comment by roland4432** [comment]
Hi @dpfahlbusch,
could you maybe share a config with configured classes? I am currently not exactly sure which part of the config you are thinking of.
Thank you.

**Comment by dpfahlbusch** [comment]
Hi @roland4432 
here is an example: https://github.com/pimcore/skeleton/blob/10.x/config/pimcore/customviews.example.php#L12

**Comment by roland4432** [comment]
I checked the part of the config. I can insert this in the config, but I have to point out, that this is **not** affecting ACL concerns, and since users can switch their perspective, it won't prevent users from creating other classes as stated in a particular perspective.

This is a permission issue and should be at least also been setup in the user / role classes permission.

**Comment by MagPim** [comment]
I also have the problem, at least I suppose this is the same problem. 
When I try to add a custom view in my perspective, this custom view (Product object in specific directory), I get an error when I then switch to this perspective. I get this message:
![image](https://user-images.githubusercontent.com/39189262/140103917-bbb9857b-ee18-4dd1-8fe1-fb54bedab97a.png)
I was never asked in the view creation which class I want in the view creation. Would that be the problem?

**Comment by MagPim** [comment]
Following my last comment: if I add the line "classes: PRDT.."  in my view yaml, then I don't have the error and I can see what I need to see.

**Comment by langert** [comment]
As the config file is in yaml now - can anyone give an example of the correct notation for a selection of object classes in yaml ?

**Comment by MagPim** [comment]
Here is what I added to make it work:
![image](https://user-images.githubusercontent.com/39189262/150803949-665d3a3e-1c5a-438b-ace9-82024b8754af.png)

**Comment by langert** [comment]
guessing the key is the unique class identifier and null the depth to show? 

classes:
 6: null
 2: null

seems to work to limit the shown objects. But my expectation, that the other folders, not having any objects of the named classes will disapear did not happen ;-)
Is it possible to name some rootfolders to be shown and hide all others?
