### ISSUE TITLE
remove testing hook to open perspective editor on load

### ISSUE THREAD

**Issue by roland4432** [pimcore/perspective-editor#6]
@fashxp where would the final space for this plugin be?

Files -> perspectives -> Editor?
Tools -> Perspective Editor?

**Comment by fashxp** [comment]
i would put it into settings menu

![image](https://user-images.githubusercontent.com/8792145/107394256-f5511780-6afb-11eb-9a54-fbb1140c9a02.png)

**Comment by roland4432** [comment]
will do :)
