### ISSUE TITLE
[Bug]: renaming perspective deletes configuration

### ISSUE THREAD

**Issue by passioneight** [pimcore/perspective-editor#71]
### Expected behavior

When renaming a perspective, the file name gets updated.

### Actual behavior

The file is deleted.

### Steps to reproduce

Just renamed a perspective from `Matomo` to `matomo`, as I wanted to stick to naming conventions (based on the `default` perspective). This effectively deleted the file.

**Comment by mcop1** [comment]
@passioneight sorry, I am not able to reproduce the problem. Which write target (PIMCORE_WRITE_TARGET_PERSPECTIVES) are you using?

**Comment by mcop1** [comment]
Closed due to inactivity, feel free to reopen the issue if needed.
