### ISSUE TITLE
[Improvement]: Add translations (and maybe icons) to "Forbidden Dashboards"

### ISSUE THREAD

**Issue by robertSt7** [pimcore/perspective-editor#74]
### Improvement description

<img width="231" alt="image" src="https://user-images.githubusercontent.com/104770750/172352925-9f737af2-588c-45a5-87a6-db00274422d9.png">

Use the same translations and icons as in the "Add Portlet-Menu" from the dashboard
![image](https://user-images.githubusercontent.com/104770750/172352798-3676db6f-81ca-4644-bccd-93c671ac7ee9.png)

**Comment by kingjia90** [comment]
I've used `pimcore.layout.portlets[portletType].prototype.getName()` in #75 and indirectly fixed this one as well.

The icons are not present though, maybe someone could provide a follow up PR for that with `iconCls: pimcore.layout.portlets[portletType].prototype.getIcon()`
